### PR TITLE
Remove possible ableist & sexist terms

### PR DESCRIPTION
**Pull request by gleuch**
Certain terms can be constructed to produce ableist &/or sexist phrases, per issue #27 .

This PR pulls out some of the more flagrant words that could be constructed into offensive phrases. It is subjective and incomplete, but should suffice for an initial start.

### CODE REVIEW

**Comment by Robbie-Cook** [comment]
Could we get this merged in @aceakash ?

**Comment by Robbie-Cook** [comment]
I see there has been no updates to this package in the last 12 months, so I have taken the liberty of forking this in to my own package - name-creator: https://www.npmjs.com/package/name-creator .\

This package implements your PR @gleuch .

Please get in touch with me if there are any problems. I am happy to expand contributors and/or point back to this package if more maintainers are added.
As it stands, I am not comfortable using this package as-is because of the offensiveness and security (your packages need updating) concerns.

**Review by aceakash — APPROVED** [review]

**Comment by aceakash** [comment]
Apologies for not looking at this PR earlier.
My GitHub notifications were misconfigured, and I only got an email when @Robbie-Cook tagged me.

**Comment by Robbie-Cook** [comment]
Hey, that's fine @aceakash , we know you are maintaining this out of the kindness of your heart! Thanks.

**Pull request merged**
